version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  shortify-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shortify-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis